package com.angrybirds.game;

public enum GameStates {
    HOME_SCREEN, CHOOSE_LEVEL_SCREEN, GAME_QUIT, LOSING_SCREEN, WINNING_SCREEN, LEVEL1SCREEN, MAIN_SCREEN, SAVED_GAME, LEVEL2SCREEN, LEVEL3SCREEN
}
